import json
from copy import deepcopy
from pathlib import Path
from collections import Counter
import pytest
from parsers.excel.pipeline import ExcelMealParser
from parsers.excel.workbook_reader import read_workbook
from parsers.excel.meal_normalizer import split_menu_text
from parsers.excel.models import CellData, SheetGrid, MenuItem, MealRecord
from parsers.excel.completeness import source_coverage, suspicious_meals
from production.completeness_audit import golden_metrics
from production.gate import production_route
from parsers.excel.layout_analyzer import LayoutProfile
from parsers.excel.table_extractor import extract_records

ROOT=Path(__file__).resolve().parents[1]
FIXTURE=ROOT/'tests/fixtures/completeness'
MANIFEST=json.loads((FIXTURE/'manifest.json').read_text(encoding='utf-8'))
GOLDEN=json.loads((FIXTURE/'golden.json').read_text(encoding='utf-8'))['slots']

@pytest.fixture(scope='module')
def results():
    return {m['document_id']:ExcelMealParser(ROOT).parse_sample(m) for m in MANIFEST}

def test_full_meal_goldens_match_source_cells_independently():
    for item in MANIFEST:
        workbook=read_workbook(ROOT/item['local_path'])
        for slot in [s for s in GOLDEN if s['document_id']==item['document_id']]:
            sheet=next(s for s in workbook.sheets if s.name==slot['sheet'])
            cells={c.coordinate:c for c in sheet.cells}
            # The expected list was hand transcribed, never generated by parser.
            actual=[i.name for address in slot['cells'] for i in split_menu_text(cells[address].text)]
            assert actual==slot['items']

def test_full_menu_list_golden_metrics(results):
    metrics=golden_metrics(GOLDEN,results)
    assert metrics['documents']==8 and metrics['meal_slots']==24
    assert metrics['menu_item_precision']==metrics['menu_item_recall']==metrics['full_meal_exact_match']==1
    assert all(s['source_cells_complete'] for s in metrics['slots'])
    # Food ground truth can be checked while ambiguous historical year stays
    # REVIEW; never weaken that existing period gate to improve sample metrics.
    for ident in {s['document_id'] for s in GOLDEN}:
        if production_route(results[ident],institution_id=results[ident]['institution_id'])!='ready':
            assert ident=='51939-51264'
            assert {i['code'] for i in results[ident]['document_issues']}=={'YEAR_INFERRED_FROM_PUBLICATION'}

def test_busan_no_last_row_only(results):
    meals=[r for r in results['61045-61178']['records'] if r['meal_date']=='2019-02-01']
    assert [len(r['menu_items']) for r in meals]==[4,4,5]
    assert all(r['source']['cells'][0].endswith('25') for r in meals)

def test_multi_row_dates_down_block_keep_same_full_meal(results):
    records=results['56195-55886']['records']
    meals=[r for r in records if r['meal_date'] in ('2016-08-01','2016-08-08') and r['meal_type']=='breakfast']
    assert len(meals)==2
    assert [i['name'] for i in meals[0]['menu_items']]==[i['name'] for i in meals[1]['menu_items']]
    assert len(meals[0]['menu_items'])==4

def test_merged_food_cells_are_not_duplicated_or_lost(results):
    record=next(r for r in results['59108-59036']['records'] if r['meal_date']=='2018-04-02' and r['meal_type']=='breakfast')
    assert record['source']['cells']==['D11','D12','D14']
    assert len(record['menu_items'])==3

def test_merged_date_range_covers_entire_block(results):
    record=next(r for r in results['65664-66430']['records'] if r['meal_date']=='2021-05-03' and r['meal_type']=='lunch')
    assert record['source']['cells']==['E4','E5','E6','E7']

def test_source_range_missing_food_forces_review():
    cells=[CellData('B2',2,2,'국','국'),CellData('B3',3,2,'김치','김치')]
    sheet=SheetGrid('S',2,3,2,2,[],cells)
    record=MealRecord('I','2026-01-01','breakfast',[MenuItem('김치','김치')],
                      {'cells':['B3'],'block_bounds':[2,3,2,2]}, {})
    coverage=source_coverage([record],sheet)
    assert not coverage['source_completeness_valid']
    assert coverage['issues'][0]['code']=='INCOMPLETE_SOURCE_RANGE'
    assert coverage['issues'][0]['missing_cells']==['B2']

def test_legitimate_single_item_is_preserved():
    sheet=SheetGrid('S',2,2,2,2,[],[CellData('B2',2,2,'비빔밥','비빔밥')])
    record=MealRecord('I','2026-01-01','lunch',[MenuItem('비빔밥','비빔밥')],
                      {'cells':['B2'],'block_bounds':[2,2,2,2]}, {})
    assert source_coverage([record],sheet)['source_completeness_valid']
    assert record.menu_items[0].name=='비빔밥'

def test_identical_three_meals_report_is_candidate_only():
    records=[{'meal_date':'2026-01-01','meal_type':meal,'menu_items':[{'name':'김치'}]}
             for meal in ('breakfast','lunch','dinner')]
    before=deepcopy(records)
    audit=suspicious_meals(records)
    assert audit['identical_three_meal_days'][0]['code']=='IDENTICAL_SINGLE_ITEM_THREE_MEALS'
    assert records==before

def test_item_metrics_do_not_confuse_precision_with_recall():
    slots=[{'document_id':'D','date':'2026-01-01','meal_type':'lunch','items':['국','반찬','김치'],'cells':['A1','A2','A3']}]
    result={'D':{'records':[{'meal_date':'2026-01-01','meal_type':'lunch','menu_items':[{'name':'김치'}],'source':{'cells':['A3']}}]}}
    metrics=golden_metrics(slots,result)
    assert metrics['menu_item_precision']==1
    assert metrics['menu_item_recall']==pytest.approx(1/3)
    assert metrics['full_meal_exact_match']==0

def test_failed_source_consistency_cannot_be_ready(results):
    result=deepcopy(results['61045-61178'])
    result['source_completeness_valid']=False
    assert production_route(result,institution_id=result['institution_id'])=='review'

def test_footer_snack_weekdays_do_not_turn_weekly_blocks_into_daily_rows(results):
    result=results['73262-75122']
    assert result['layout_profiles'][0]['detected_layout_family']=='weekday_blocks_meal_columns'
    meals=[r for r in result['records'] if r['meal_date']=='2024-03-03']
    assert [len(r['menu_items']) for r in meals]==[4,4,4]
    assert all(max(int(''.join(c for c in address if c.isdigit())) for address in r['source']['cells'])<=31
               for r in result['records'])

def test_supplement_only_single_items_are_not_claimed_as_complete_meals(results):
    result=results['74300-76354']
    assert any(i['code']=='SUPPLEMENTARY_ONLY_TABLE' for i in result['document_issues'])
    assert production_route(result,institution_id=result['institution_id'])=='review'
    # Do not delete genuine one-item source content; keep it available for review.
    assert any([i['name'] for i in r['menu_items']]==['우유'] for r in result['records'])

def test_final_food_row_beyond_weekday_label_merge_is_not_omitted():
    # The label ends at row 4, but food continues through row 5 before footer.
    cells=[CellData('B1',1,2,'아침','아침'),
           CellData('A2',2,1,'토','토',merged_range='A2:A4'),
           CellData('B2',2,2,'국','국'), CellData('B3',3,2,'달걀','달걀'),
           CellData('B4',4,2,'김치','김치'), CellData('B5',5,2,'채소샐러드','채소샐러드'),
           CellData('A6',6,1,'간식 안내','간식 안내',merged_range='A6:B6')]
    sheet=SheetGrid('S',1,6,1,2,[],cells)
    profile=LayoutProfile('weekday_blocks_meal_columns','high',[],'S',{'breakfast':'B1'})
    records=extract_records(sheet,profile,{'institution_id':'I'},'xlsx',2025,8)
    assert records
    assert all([i.name for i in r.menu_items]==['국','달걀','김치','채소샐러드'] for r in records)
    assert all(r.source['cells']==['B2','B3','B4','B5'] for r in records)

def test_uncertain_juvenile_supplement_scope_is_review_not_failure(results):
    result=results['75768-78054']
    assert any(i['code']=='SUPPLEMENTARY_SCOPE_UNCERTAIN' for i in result['document_issues'])
    assert result['status']=='PARTIAL'
    assert production_route(result,institution_id=result['institution_id'])=='review'
    assert result['source_completeness_valid']
    assert any([i['name'] for i in r['menu_items']]==['우유'] for r in result['records'])

def test_explicit_staff_fallback_never_publishes_as_inmate_meals(results):
    result=results['72303-74034']
    assert any(i['code']=='STAFF_TABLE_SELECTED' for i in result['document_issues'])
    assert result['records'] and result['status']=='PARTIAL'
    assert production_route(result,institution_id=result['institution_id'])=='review'
